version: "3.8"

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    image: maxrollundev/php-fpm-dev-8.0
    volumes:
      - ./:/var/www/app
    environment:
      APP_ENV: dev

  php-openapi-generator:
    image: maxrollundev/php-openapi-generator:8.0
    volumes:
      - ./:/var/www/app