openapi: 3.0.0
info:
  version: "1"
  title: "Butler"
servers:
  - url: http://localhost:8080/api
  - url: http://host.docker.internal:8080/api
tags:
- name: "buttler"
- name: "buttler REST"
paths:
  /greetings:
    get:
      tags:
      - "buttler"
      operationId: "greetRequester"
      # parameters:
      # - name: "name"
      #   in: "query"
      #   required: true
      #   schema:
      #     type: string
      #     example: 'Mikola'
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    required:
                      - message
                    properties:
                      message:
                        type: string
                        example: 'Greetings Mikola'